# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storageServer/storageServer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!storageServer/storageServer.proto\"+\n\x0bupload_file\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\"\x19\n\tfile_path\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x15\n\x05reply\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\"\x1c\n\nfileStream\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x18\n\x08\x66ileList\x12\x0c\n\x04list\x18\x01 \x01(\t2\xa6\x02\n\rstorageServer\x12%\n\tsynUpload\x12\x0c.upload_file\x1a\x06.reply\"\x00(\x01\x12\"\n\x06upload\x12\x0c.upload_file\x1a\x06.reply\"\x00(\x01\x12\'\n\x08\x64ownload\x12\n.file_path\x1a\x0b.fileStream\"\x00\x30\x01\x12\x1d\n\x02ls\x12\n.file_path\x1a\t.fileList\"\x00\x12 \n\x05lsall\x12\n.file_path\x1a\t.fileList\"\x00\x12\x1d\n\x05mkdir\x12\n.file_path\x1a\x06.reply\"\x00\x12!\n\tsynDelete\x12\n.file_path\x1a\x06.reply\"\x00\x12\x1e\n\x06\x64\x65lete\x12\n.file_path\x1a\x06.reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storageServer.storageServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOAD_FILE']._serialized_start=37
  _globals['_UPLOAD_FILE']._serialized_end=80
  _globals['_FILE_PATH']._serialized_start=82
  _globals['_FILE_PATH']._serialized_end=107
  _globals['_REPLY']._serialized_start=109
  _globals['_REPLY']._serialized_end=130
  _globals['_FILESTREAM']._serialized_start=132
  _globals['_FILESTREAM']._serialized_end=160
  _globals['_FILELIST']._serialized_start=162
  _globals['_FILELIST']._serialized_end=186
  _globals['_STORAGESERVER']._serialized_start=189
  _globals['_STORAGESERVER']._serialized_end=483
# @@protoc_insertion_point(module_scope)
