# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manageServer/manageServer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmanageServer/manageServer.proto\"2\n\nserverInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\x16\n\x08serverId\x12\n\n\x02id\x18\x01 \x01(\x05\"@\n\x08\x66ileInfo\x12\x10\n\x08rootPath\x18\x01 \x01(\t\x12\x10\n\x08serverId\x18\x02 \x01(\x05\x12\x10\n\x08\x66ilePath\x18\x03 \x01(\t\"\x1c\n\x08\x66ilePath\x12\x10\n\x08\x66ilePath\x18\x01 \x01(\t\"\x1a\n\nserverpath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x12\n\x05\x65mpty\x12\t\n\x01\x65\x18\x01 \x01(\x05\".\n\x08lockInfo\x12\x10\n\x08\x63lientId\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilePath\x18\x02 \x01(\t\"\x18\n\x08ma_reply\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\"\'\n\nserverList\x12\x19\n\x04list\x18\x01 \x03(\x0b\x32\x0b.serverInfo\"\'\n\tlockReply\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t\";\n\x0bsearchReply\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08serverId\x18\x02 \x01(\x05\x12\x0c\n\x04\x64one\x18\x03 \x01(\x05\x32\xcb\x02\n\x10managementServer\x12(\n\x0cserverOnline\x12\x0b.serverInfo\x1a\t.ma_reply\"\x00\x12\'\n\rserverOffline\x12\t.serverId\x1a\t.ma_reply\"\x00\x12&\n\rgetServerList\x12\x06.empty\x1a\x0b.serverList\"\x00\x12#\n\x08lockFile\x12\t.lockInfo\x1a\n.lockReply\"\x00\x12%\n\nunlockFile\x12\t.lockInfo\x1a\n.lockReply\"\x00\x12!\n\x07\x61\x64\x64\x46ile\x12\t.fileInfo\x1a\t.ma_reply\"\x00\x12\'\n\nsearchFile\x12\t.filePath\x1a\x0c.searchReply\"\x00\x12$\n\ndelectFile\x12\t.filePath\x1a\t.ma_reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manageServer.manageServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVERINFO']._serialized_start=35
  _globals['_SERVERINFO']._serialized_end=85
  _globals['_SERVERID']._serialized_start=87
  _globals['_SERVERID']._serialized_end=109
  _globals['_FILEINFO']._serialized_start=111
  _globals['_FILEINFO']._serialized_end=175
  _globals['_FILEPATH']._serialized_start=177
  _globals['_FILEPATH']._serialized_end=205
  _globals['_SERVERPATH']._serialized_start=207
  _globals['_SERVERPATH']._serialized_end=233
  _globals['_EMPTY']._serialized_start=235
  _globals['_EMPTY']._serialized_end=253
  _globals['_LOCKINFO']._serialized_start=255
  _globals['_LOCKINFO']._serialized_end=301
  _globals['_MA_REPLY']._serialized_start=303
  _globals['_MA_REPLY']._serialized_end=327
  _globals['_SERVERLIST']._serialized_start=329
  _globals['_SERVERLIST']._serialized_end=368
  _globals['_LOCKREPLY']._serialized_start=370
  _globals['_LOCKREPLY']._serialized_end=409
  _globals['_SEARCHREPLY']._serialized_start=411
  _globals['_SEARCHREPLY']._serialized_end=470
  _globals['_MANAGEMENTSERVER']._serialized_start=473
  _globals['_MANAGEMENTSERVER']._serialized_end=804
# @@protoc_insertion_point(module_scope)
